# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hotelarthur

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5a9a309d7a7646339760e5507330f6a0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a67b2ebce83342a78ce1af33c92ec428 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5a9a309d7a7646339760e5507330f6a0 }}/arthurhotel:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hotelarthur'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_924707a8641a4cfda61069151a619baa }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5a9a309d7a7646339760e5507330f6a0 }}/arthurhotel:${{ github.sha }}'